##
## Utils 2.0 Configuration
##

server:
  # This server's name.
  name: Something

  # This server's owner.
  owner: Someone
  
  # This server's forum.
  forum: http://somethingelse.net
  
  # This server's website.
  website: http://something.com
  
  # If the /apply command gives information [true/false]
  canapply: true
  
  # Disabling broadcasting of punishment commands [true/false] 
  disablepunishbroadcasts: true
  
  # The filter for censoring certain words. [true/false]
  filter: true
  
  # The list of words for your filter. To block a word if it is alone
censored_words:
  - fuck
  - shit
  - cock
  - dick
  - \bas(s+)\b
  - pussy
  - penis
  - fuk
  - fuc
  - bitch
  - titties
  - tit


banning:

  # Ban appeal message. If your server doesn't support appeals, set to "none"
  appeal_url: none


admins: []
