##
## Utils 2.0 Configuration
##

server:
  # This server's name.
  name: Something

  # This server's owner.
  owner: Someone
  
  # This server's forum.
  forum: http://somethingelse.net
  
  # This server's website.
  website: http://something.com
  
  # If the /apply command gives information [true/false]
  canapply: true
  
  # Disabling broadcasting of punishment commands [true/false] 
  disablepunishbroadcasts: true
  
  # The filter for censoring certain words. [true/false]
  filter: true
  
  # The list of words for your filter. To block a word if it is alone
censored_words:
  - anus
  - arse
  - arsehole
  - dick
  - \bas(s+)\b
  - ass-hat
  - ass-jabber
  - ass-pirate
  - assbag
  - assbandit
  - assbanger
  - assbite
  - assclown
  - asscock
  - asscracker
  - assfuck
  - assfucker
  - assgoblin
  - asshat
  - asshole
  - asshopper
  - assjacker
  - asslick
  - asslicker
  - assmonkey
  - assmunch
  - assmuncher
  - assnigger
  - asspirate
  - assshit
  - assshole
  - asssucker
  - asswad
  - asswipe
  - axwound
  - bampot
  - bastard
  - beaner
  - bitch
  - bitchass
  - bitches
  - bitchtits
  - bitchy
  - blowjob
  - bollocks
  - bollox
  - boner
  - brotherfucker
  - bullshit
  - bumblefuck
  - buttfucka
  - buttfucker
  - fuck
  - shit
  - cock
  - dick
  - \bas(s+)\b
  - pussy
  - penis
  - fuk
  - fuc
  - bitch
  - titties
  - tit



banning:

  # Ban appeal message. If your server doesn't support appeals, set to "none"
  appeal_url: none

