##
## Utils 2.0 Configuration
##

server:
  # This server's name.
  name: Something

  # This server's owner.
  owner: Someone

  # This server's website.
  website: http://something.com
  
  # Prefix for various things, color codes supported.
  prefix: [Default]
  
  # The filter for censoring certain words. [on/off]
  filter: on
  
  # The list of words for your filter.
censored_words:
  - fuck
  - shit
  - cock
  - dick
  - ass
  - pussy
  - penis
  - fuk
  - fuc
  - bitch
  - fucker
  - titties
  - tits
  - titts
  

banning:

  # Ban appeal message. If your server doesn't support appeals, set to "none"
  appeal_url: none


admins: [Someone]
