name: Utils
version: 1.0
description: Revamp of Utils!
loadbefore: [Essentials]
authors: [Prozza, Adaptified]
softdepend: [Aero]
main: me.adaptified.utils.Utils
commands:
    ban:
        description: Ban a user
        usage: /<command> [player] [reason]
    banip:
        description: Ban an IP
        usage: /<command> [IP] [reason]
    kick:
        description: Kick a player
        usage: /<command> [player] [reason]
    mute:
        description: Mute a player
        usage: /<command> <player>
    forums:
        description: Get the server's forum link.
        usage: /<command>
    staff:
        description: Lists the servers staff
        usage: /<command>
        aliases: admins